import Foundation
import RAW
import RAW_sha256

/// server-side helpers for serving the wasm client artifact: locating the
/// release product and content-addressing it. the framework emits bytes via
/// `HTMLDocument(clientMode:)`; serving (routes, cache headers) is the host
/// server's job — these helpers make computing the `webui-wasm` url trivial.
///
/// the artifact's hash is known at build time (`WebUIWasmInfo`, generated by
/// the `WebUIWasmPlugin` build-tool plugin) so the immutable-cached route is
/// stable per-build; the runtime helpers below fall back to hashing the bytes
/// when the carrier is absent (no host build ran the wasm plugin).
public enum WebUIBoot {
	/// whether the wasm client artifact was present when this binary was built.
	public static var wasmAvailable: Bool {
		WebUIWasmInfo.present
	}

	/// the build-time sha-256 (lowercase hex) of the served client artifact.
	public static var wasmSHA256: String {
		WebUIWasmInfo.sha256
	}

	/// the release `WebUIClient.wasm` product url under `.build`, or `nil`
	/// when the artifact has not been built (the gates build it first).
	public static func wasmProductURL() -> URL? {
		wasmProductURL(productName: "WebUIClient")
	}

	/// the release wasm product url under `.build` for an arbitrary product
	/// name (consumers who cross-build their own client under a different
	/// name — `swift package --disable-sandbox plugin wasm-client --product
	/// TheirClient` — resolve their artifact with this).
	public static func wasmProductURL(productName: String) -> URL? {
		let candidate = URL(fileURLWithPath: ".build/out/Products/Release-webassembly-wasm32/\(productName).wasm")
		return FileManager.default.fileExists(atPath: candidate.path) ? candidate : nil
	}

	/// sha-256 lowercase hex over a byte string; an empty string signals "no
	/// bytes". used to content-address the artifact so the immutable-cache
	/// route is automatically cache-busted when the binary changes
	/// (`/__assets/app.<hash>.wasm`).
	public static func wasmHash(of bytes: [UInt8]) -> String {
		var hasher = RAW_sha256.Hasher()
		bytes.withUnsafeBytes { hasher.update($0) }
		var digest = [UInt8](repeating: 0, count: 32)
		do {
			try digest.withUnsafeMutableBytes { buffer in
				try hasher.finish(into: buffer.baseAddress!)
			}
			return bytesToHex(digest)
		} catch {
			return ""
		}
	}
}
