// MARK: - the live-data macro surface (MACRO_DX features A–C)
//
// additive: the frozen protocols in `LiveRegions.swift` and `LiveState.swift`
// are untouched, and every macro here is OPTIONAL — the hand-written
// conformance keeps compiling and keeps its exact behavior (the substitution
// law, §3.0). the declarations are inert metadata; the implementations live in
// the `WebUIServerMacros` compiler plugin.

/// generate the ``LiveRegion`` conformance for a type: `id` from the attribute,
/// `cadence` from the attribute (or `nil`), and `source` from the property
/// marked with ``RegionState()``.
///
/// the author writes what the type IS and what it RENDERS:
///
/// ```swift
/// @LiveRegion(id: "count")
/// struct Counter {
///     @RegionState let box: LiveBox<Int>
///     func render() async -> String? { "<div id=\"count\">\(box.value)</div>" }
/// }
/// ```
///
/// the hand-written spelling — declaring `id`, `cadence`, `source` and the
/// conformance yourself — remains valid and is byte-identical on the wire.
@attached(member, names: named(id), named(cadence), named(source))
@attached(extension, conformances: LiveRegion)
public macro LiveRegion(id: String, cadence: Duration? = nil) =
	#externalMacro(module: "WebUIServerMacros", type: "LiveRegionMacro")

/// mark the ONE stored property that is the region's `source` — the value the
/// registry subscribes at start, so a change wakes the region with no wiring.
///
/// this is a marker: it never expands alone, and `@LiveRegion`'s member scan is
/// what reads it. marking none is legal and means `source == nil` (the
/// protocol default); marking two is a diagnostic.
@attached(peer)
public macro RegionState() =
	#externalMacro(module: "WebUIServerMacros", type: "RegionStateMarker")

/// generate the registry assembly for a live-data group: `registry` becomes a
/// ``WebUILiveRegions`` built from the group's region properties, in
/// declaration order.
///
/// the member list IS the registry, so this is a member macro — an attached
/// peer/body macro receives a member-less type shell.
///
/// classification is syntactic: a property is a region when its written type or
/// its initializer's callee names a region type (a nested type carrying
/// `@LiveRegion`, or `ClosureLiveRegion` / `StateLiveRegion`), and it is
/// skipped when that name is a known state (a nested `@LiveState` type,
/// `LiveBox`, `LiveNotifier`). anything else is diagnosed.
@attached(member, names: named(registry))
public macro LiveRegions() =
	#externalMacro(module: "WebUIServerMacros", type: "LiveRegionsMacro")

/// generate a ``LiveState`` conformance for an actor: a `nonisolated
/// subscribe` forwarding to an embedded `LiveNotifier`, and a `notify()` that
/// wakes the region's registry subscription.
///
/// `nonisolated` is generated by construction, so the synchronous hop onto a
/// busy actor — the failure mode that stalls `start()` — cannot be written by
/// accident.
///
/// ```swift
/// @LiveState
/// actor Feed {
///     private var value = 0
///     func bump() { value += 1; notify() }
///     func snapshot() -> Int { value }
/// }
/// ```
@attached(member, names: named(subscribe), named(notify), named(liveNotifier))
@attached(extension, conformances: LiveState)
public macro LiveState() =
	#externalMacro(module: "WebUIServerMacros", type: "LiveStateMacro")