import Foundation
import Testing
import WebUI
import WebUIDesignSystem

// MARK: - DesignToken generation integrity
//
// DesignToken is generated by WebUIAssetTool from design-system.css. this
// suite pins the generated vocabulary to the shipped stylesheet: a token gain
// or loss in the css without a regeneration (the plugin regenerates on every
// build) fails here, and a hand-edited generated file is caught by
// round-tripping every rawValue back into the css.

/// independent minimal parse of the css: strips comments, tracks the selector
/// stack, and collects `--name:` declarations that sit inside a `:root`
/// block. deliberately written separately from the generator so drift between
/// the two parsers surfaces as a test failure.
func isTokenNameChar(_ c: Character) -> Bool {
	c.isLetter || c.isNumber || c == "-" || c == "_"
}

func parseRootTokensFromDesignCSS(_ css: String) -> Set<String> {
	var out = ""
	var i = css.startIndex
	while i < css.endIndex {
		let c = css[i]
		if c == "/", css.index(after: i) != css.endIndex, css[css.index(after: i)] == "*" {
			var j = css.index(after: i)
			j = css.index(after: j)
			while j != css.endIndex {
				if css[j] == "*", css.index(after: j) != css.endIndex, css[css.index(after: j)] == "/" {
					j = css.index(after: j)
					j = css.index(after: j)
					break
				}
				j = css.index(after: j)
			}
			i = j
			continue
		}
		out.append(c)
		i = css.index(after: i)
	}

	var stack: [String] = []
	var pending = ""
	var names = Set<String>()
	i = out.startIndex
	while i < out.endIndex {
		let c = out[i]
		if c == "{" {
			stack.append(pending.trimmingCharacters(in: .whitespacesAndNewlines))
			pending = ""
			i = out.index(after: i)
		} else if c == "}" {
			if !stack.isEmpty { stack.removeLast() }
			pending = ""
			i = out.index(after: i)
		} else if c == ";" {
			pending = ""
			i = out.index(after: i)
		} else if c == "-", out.index(after: i) != out.endIndex, out[out.index(after: i)] == "-" {
			var j = out.index(after: i)
			j = out.index(after: j)
			var name = ""
			while j != out.endIndex, isTokenNameChar(out[j]) {
				name.append(out[j])
				j = out.index(after: j)
			}
			var k = j
			while k != out.endIndex, out[k] == " " || out[k] == "\t" {
				k = out.index(after: k)
			}
			if !name.isEmpty, k != out.endIndex, out[k] == ":", stack.contains(":root") {
				names.insert(name)
			}
			i = j
		} else {
			pending.append(c)
			i = out.index(after: i)
		}
	}
	return names
}

@Suite("DesignToken generation integrity")
struct DesignTokenIntegrityTests {

	@Test("every generated rawValue is declared on :root in the shipped css")
	func rawValuesExistInCss() throws {
		let css = try String(contentsOfFile: packageRootURL().appendingPathComponent("designer/assets/design-system.css").path, encoding: .utf8)
		for token in DesignToken.allCases {
			#expect(css.contains("--\(token.rawValue):"), "missing declaration for --\(token.rawValue)")
		}
	}

	@Test("generated case count matches an independent parse of the shipped css")
	func caseCountMatches() throws {
		let css = try String(contentsOfFile: packageRootURL().appendingPathComponent("designer/assets/design-system.css").path, encoding: .utf8)
		let expected = parseRootTokensFromDesignCSS(css)
		let actual = Set(DesignToken.allCases.map(\.rawValue))
		#expect(actual == expected, "DesignToken has \(actual.count) tokens; shipped css declares \(expected.count)")
	}

	@Test("case names are unique and identifier-safe")
	func caseNamesAreSafe() {
		let names = DesignToken.allCases.map(\.rawValue)
		#expect(Set(names).count == names.count, "duplicate raw values")
		#expect(DesignToken.allCases.count == DesignToken.tokenCount, "tokenCount (\(DesignToken.tokenCount)) diverges from allCases (\(DesignToken.allCases.count))")
		for token in DesignToken.allCases {
			#expect(token.cssVariable == "--\(token.rawValue)")
		}
	}

	@Test("every token's case name is the camelCased raw value")
	func caseNameMatchesCamelCase() {
		for token in DesignToken.allCases {
			let expected = camelCaseOf(token.rawValue)
			#expect(String(describing: token) == expected, "\(token.rawValue) → '\(token)' but camelCase is '\(expected)'")
		}
	}

	@Test("the razor-sharp theme vocabulary is present")
	func knownSpellings() {
		// the exact tokens the arc-agent-style dark theme needs are first-class cases.
		#expect(DesignToken.colorPrimarySolid.rawValue == "color-primary-solid")
		#expect(DesignToken.colorPrimarySolid.cssVariable == "--color-primary-solid")
		#expect(DesignToken.colorBg.rawValue == "color-bg")
		#expect(DesignToken.colorText.rawValue == "color-text")
		#expect(DesignToken.radiusCard.rawValue == "radius-card")
		#expect(DesignToken.fontSans.rawValue == "font-sans")
		#expect(DesignToken.zToast.rawValue == "z-toast")
		#expect(DesignToken.colorChart1.rawValue == "color-chart-1")
	}

	private func camelCaseOf(_ name: String) -> String {
		let parts = name.split(separator: "-", omittingEmptySubsequences: true)
		guard let first = parts.first else { return name }
		var result = String(first)
		for part in parts.dropFirst() {
			result += part.prefix(1).uppercased() + part.dropFirst()
		}
		return result
	}
}
