#!/usr/bin/env node
// designer/probes/g-styling.mjs  — lane G's styling probe (MACRO_DX G1+G3).
//
// two halves, both reproducible from committed artifacts:
//
//   1. the RENDERED GAP: builds a scratch executable OUTSIDE the repo
//      (~/fleet/macro-dx/g-styling-probe — the lane S spike pattern) against
//      THIS clone over a local path dependency, renders VStack(spacing: 7),
//      HStack(spacing: 7) and VStack(spacing: 8), and asserts:
//        - the 7px stacks carry an inline `gap:7px;` and NO dead spacing-7
//          class (the G1 fix: off-scale values are inline, byte-shaped like
//          Grid), and
//        - the 8px stack is byte-identical to the pre-G1 class emission
//          (in-scale values stay on the shipped `.spacing-N` utilities).
//      the probe (re)writes the scratch manifest/source itself, so the gap
//      proof runs against whatever the clone currently holds.
//
//   2. the MARKUP-DEBT NUMBERS: runs the ONE lint verb's additive audit over
//      the demo tree (Sources/WebUIExample) and prints the five per-file
//      metrics + totals; then proves the committed baseline ratchet is green
//      on the repo (Sources, WebUIDesignSystemCore reported-not-ratcheted),
//      then proves a deliberately-grown fixture trips `--fail-on-increase`.
//
// usage:
//   node designer/probes/g-styling.mjs
//      (no server, no lane port)

import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, mkdtempSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const SCRATCH = join(dirname(ROOT), "g-styling-probe");

let pass = 0, fail = 0;
const ok = (m) => { pass++; console.log(`  PASS ${m}`); };
const bad = (m) => { fail++; console.log(`  FAIL ${m}`); };

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { encoding: "utf8", ...opts });
  return { code: r.status, out: r.stdout ?? "", err: r.stderr ?? "" };
}

// ── 1. the rendered gap ──────────────────────────────────────────────────────
console.log("g-styling: rendered-gap probe (VStack(spacing: 7) is a real gap)");

const manifest = `// swift-tools-version:6.0
// the g-styling rendered-gap probe's scratch package (MACRO_DX lane G).
// generated by designer/probes/g-styling.mjs; lives outside the repo.
import PackageDescription

let pkg = Package(
    name: "g-styling-probe",
    platforms: [.macOS(.v15)],
    dependencies: [
        .package(path: ${JSON.stringify(ROOT)}),
    ],
    targets: [
        .executableTarget(
            name: "Probe",
            dependencies: [.product(name: "WebUICore", package: "lane-g")]
        ),
    ]
)
`;
const mainSource = `import WebUICore

// the rendered-gap probe fixture (MACRO_DX G1): prints the exact rendered bytes
// of one off-scale and two in-scale stacks so g-styling.mjs can assert the gap
// is real and the class emission is byte-identical.
let v7 = VStack(spacing: 7) { Text("a"); Text("b") }
let v8 = VStack(spacing: 8) { Text("a"); Text("b") }
let h7 = HStack(spacing: 7) { Text("a"); Text("b") }
print("V7=" + v7.render())
print("V8=" + v8.render())
print("H7=" + h7.render())
`;

mkdirSync(join(SCRATCH, "Sources", "Probe"), { recursive: true });
writeFileSync(join(SCRATCH, "Package.swift"), manifest);
writeFileSync(join(SCRATCH, "Sources", "Probe", "main.swift"), mainSource);

const built = run("swift", ["build"], { cwd: SCRATCH });
if (built.code !== 0) {
  bad(`scratch package failed to build against ${ROOT}`);
  console.log(built.err.slice(-2000));
} else {
  ok("scratch package builds against the clone");
  const binary = join(SCRATCH, ".build", "debug", "Probe");
  const rendered = run(binary, []);
  const v7 = (rendered.out.match(/V7=([\s\S]*?)V8=/)?.[1] ?? "").trim();
  const v8 = (rendered.out.match(/V8=([\s\S]*?)H7=/)?.[1] ?? "").trim();
  const h7 = (rendered.out.match(/H7=([\s\S]*)$/)?.[1] ?? "").trim();
  const inScaleRef = '<div class="vstack spacing-8 align-flex-start">\nab\n</div>';
  const offScaleShape = '<div class="vstack align-flex-start" style="gap:7px;">\nab\n</div>';
  const hOffScaleShape = '<div class="hstack align-center" style="gap:7px;">\nab\n</div>';

  if (v7 === offScaleShape) ok("VStack(spacing: 7) renders the inline gap, dead class dropped");
  else bad(`VStack(spacing: 7) rendered ${JSON.stringify(v7)}`);
  if (h7 === hOffScaleShape) ok("HStack(spacing: 7) renders the inline gap, dead class dropped");
  else bad(`HStack(spacing: 7) rendered ${JSON.stringify(h7)}`);
  if (v8 === inScaleRef) ok("VStack(spacing: 8) is byte-identical to the pre-G1 class emission (no inline style)");
  else bad(`VStack(spacing: 8) rendered ${JSON.stringify(v8)}`);
  if (v7.includes("spacing-7") || h7.includes("spacing-7")) bad("a dead spacing-7 class is still emitted");
  else ok("no spacing-7 class anywhere (the shipped sheet ships no .spacing-7 rule)");
}

// ── 2. the markup-debt numbers (G3, additive to the one lint) ───────────────
console.log("g-styling: markup-debt audit on the demo tree + the ratchet");

const toolCandidates = [
  join(ROOT, ".build", "out", "Products", "Debug", "WebUIContinuumTool"),
  join(ROOT, ".build", "debug", "WebUIContinuumTool"),
];
const tool = toolCandidates.find((p) => existsSync(p));
if (!tool) {
  bad("WebUIContinuumTool binary not found — run `swift build` first");
} else {
  const demo = run(tool, ["lint", "--sources", "Sources/WebUIExample", "--debt-sources", "Sources/WebUIExample"], { cwd: ROOT });
  if (demo.code !== 0) bad(`demo-tree audit didn't exit cleanly (${demo.code})`);
  const demoRows = (demo.out.match(/Sources\/WebUIExample\S+\.swift: .*/g) ?? []).join(" / ");
  const demoTotals = (demo.out.match(/totals: .*/)?.[0] ?? "").trim();
  console.log(`  demo tree: ${demoRows}`);
  console.log(`  demo tree: ${demoTotals}`);
  const tags = Number(/tags=(\d+)/.exec(demoTotals)?.[1] ?? -1);
  const classes = Number(/class=(\d+)/.exec(demoTotals)?.[1] ?? -1);
  const styles = Number(/style=(\d+)/.exec(demoTotals)?.[1] ?? -1);
  const colors = Number(/colors=(\d+)/.exec(demoTotals)?.[1] ?? -1);
  const vars = Number(/var=(\d+)/.exec(demoTotals)?.[1] ?? -1);
  if ([tags, classes, styles, colors, vars].every((n) => n >= 0)) ok(`demo tree totals tags=${tags} class=${classes} style=${styles} colors=${colors} var=${vars}`);
  else bad("could not parse the demo-tree totals from the audit output");

  // the committed-baseline ratchet over the whole Sources tree.
  const baseline = join(ROOT, "designer", "markup-debt.json");
  if (!existsSync(baseline)) bad("committed baseline designer/markup-debt.json missing");
  else {
    const ratchet = run(tool, ["lint", "--sources", "Sources/WebUIExample", "--debt-sources", "Sources", "--baseline", baseline, "--fail-on-increase"], { cwd: ROOT });
    const allow = (ratchet.out.match(/allowlisted: .*?\)/)?.[0] ?? "").trim();
    if (ratchet.code === 0) ok(`repo ratchet green (--fail-on-increase, exit 0); ${allow}`);
    else bad(`repo ratchet TRIPPED (exit ${ratchet.code}) — baseline drifted`);
  }

  // a deliberately-grown fixture trips --fail-on-increase (the accept).
  const grown = mkdtempSync(join(tmpdir(), "g3-grown-"));
  writeFileSync(join(grown, "Grown.swift"), 'let html = "<div class=\\"grown\\"><span>#aabbcc var(--space-8) style=\\"gap:9px;\\"</span></div>"\n');
  const trip = run(tool, ["lint", "--sources", grown, "--debt-sources", grown, "--baseline", baseline, "--fail-on-increase"], { cwd: ROOT });
  if (trip.code !== 0) ok("a grown fixture (new file with markup) trips --fail-on-increase");
  else bad("a grown fixture did NOT trip --fail-on-increase (ratchet is porous)");
  rmSync(grown, { recursive: true, force: true });
}

console.log(`\ng-styling: ${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
